[build-system]
requires = ["setuptools>=61.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"

[project]
name = "text-preprocessing-toolkit"
version = "0.0.1"
description = "Automate text preprocessing tasks like tokenization, lemmatization, stop word removal, and normalization."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Gaurav-Jaiswal-1", email = "jaiswalgaurav863@gmail.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Text Processing :: Linguistic",
]
urls = { 
    "homepage" = "https://github.com/Gaurav-Jaiswal-1/text-preprocessing-toolkit" 
}

dependencies = [
    # Core dependencies for text preprocessing
    "nltk>=3.8.1",
    "spacy>=3.6.0",
]

[project.optional-dependencies]
dev = [
    # Testing and coverage
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    # Linting and formatting
    "flake8>=6.0.0",
    "black>=23.1.0",
    # Type checking
    "mypy>=0.991",
    # Documentation
    "sphinx>=7.1.2",
    "sphinx-rtd-theme>=1.2.0",
]

[project.scripts]
# CLI entry point
"text-preprocess" = "text_preprocessing_toolkit.main:main"

[tool.pytest.ini_options]
# Pytest configuration for tests and coverage
addopts = "--cov=text_preprocessing_toolkit --cov-report=term-missing --cov-report=html"
testpaths = ["tests"]

[tool.flake8]
# Flake8 linting configuration
max-line-length = 88
exclude = ".git,__pycache__,docs,build,dist"

[tool.mypy]
# Mypy type checking configuration
files = ["text_preprocessing_toolkit"]
ignore_missing_imports = true
