name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']  # Test on multiple Python versions

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      # Run tests
      - name: Run tests
        run: tox

  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      # Install linting tools
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # Run linting
      - name: Run linting
        run: |
          black --check .
          flake8 .

  type-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      # Install type-checking tools
      - name: Install type-checking dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      # Run type checking
      - name: Run type checking
        run: mypy src/Text_Preprocessing_Toolkit

  docs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      # Install dependencies for docs generation
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      # Build documentation
      - name: Build documentation
        run: |
          sphinx-build -b html docs/ build/docs
