# Workflow to build and publish Python package to PyPI for Python versions 3.8 through 3.11

name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment with matrix version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to PyPI only for one version (e.g., 3.11) to avoid duplicate uploads
      - name: Publish package to PyPI
        if: matrix.python-version == '3.11'
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # Optional: Notify on success
      - name: Notify Success
        if: success() && matrix.python-version == '3.11'
        run: echo "🎉 Package successfully published to PyPI for Python ${{ matrix.python-version }}!"
